#!bin/bash
GIT_DIR=$HOME/src/dotfiles
if [ ! -d $GIT_DIR ]
then
    mkdir -p $GIT_DIR
fi
git init --bare $GIT_DIR
alias config="git --git-dir=$GIT_DIR/ --work-tree=$HOME"
git --git-dir=$GIT_DIR/ --work-tree=$HOME
echo "alias config=\"git --git-dir=$GIT_DIR/ --work-tree=$HOME\"" >> $HOME/.bashrc
